name = "cloudflare-chatwoot-sync"
main = "src/entry.py"
compatibility_flags = ["python_workers"]
compatibility_date = "2024-07-26"
send_metrics = false

[vars]
CHATWOOT_URL = "https://chat.iditelesom.org"
CHATWOOT_ACCOUNT_ID = "1"
CLOUDFLARE_ACCOUNT_ID = "1350c815b1d782d01eb6bd43eded4b01"
CLOUDFLARE_ACCESS_GROUP_ID = "e74387ef-b4ff-48c9-a714-127c15567ab9"
CLOUDFLARE_ACCESS_GROUP_NAME = "Chatwoot Users"
INACTIVITY_DAYS_THRESHOLD = "7"
DEBUG = "false"

[triggers]
# Schedule cron triggers:
# - At every 15 minutes
crons = [ "*/15 * * * *" ]